# Generated by Django 5.1.2 on 2024-10-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission_Name', models.CharField(max_length=100)),
                ('permit_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
