# Generated by Django 5.1.2 on 2024-10-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Birth_Date', models.DateField()),
                ('Registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
