# Generated by Django 5.1.2 on 2024-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Specialization', models.CharField(max_length=100)),
                ('Hire_date', models.DateField()),
            ],
        ),
    ]
