# Generated by Django 5.1.2 on 2024-10-28 15:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('hire_date', models.DateField()),
                ('Menbers_Type', models.CharField(max_length=200)),
                ('id_Roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
    ]
