# Generated by Django 5.1.2 on 2024-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partner_Name', models.CharField(max_length=100)),
                ('Agreement_Date', models.DateField()),
                ('Expiration_Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Contact_Info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
