# Generated by Django 5.1.2 on 2024-10-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_maintenance_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=100)),
                ('security_level', models.CharField(max_length=100)),
                ('assigned_area', models.CharField(max_length=100)),
                ('Team_Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
    ]
