# Generated by Django 5.1.2 on 2024-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_security_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservation_Type', models.CharField(max_length=50)),
                ('Reservation_Date', models.DateField()),
                ('Time_Start', models.TimeField()),
                ('Time_End', models.TimeField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
