# Generated by Django 5.1.2 on 2024-10-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoccerField_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=100)),
                ('number_of_players', models.IntegerField()),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
        ),
    ]
