# Generated by Django 5.1.2 on 2024-10-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_soccerfield_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworking_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_number', models.IntegerField()),
                ('equipment_required', models.CharField(max_length=100)),
                ('reservation_duration', models.CharField(max_length=100)),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
        ),
    ]
