# Generated by Django 5.1.2 on 2024-10-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_permission_slip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Early_Exit_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField()),
                ('reason_for_exit', models.TextField()),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_exit_permissions', to='api.permission_slip')),
            ],
        ),
    ]
